package:
  name: rank_filter
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}{{ '+' + environ.get('GIT_DESCRIBE_NUMBER', '0') + '.' + environ.get('GIT_DESCRIBE_HASH', '0') if environ.get('GIT_DESCRIBE_NUMBER', '0') != '0' else "" }}

source:
  git_url: ..

build:
  script_env:
    - EXT_CC
    - EXT_CXX

  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - patchelf >=0.8    # [linux]

  host:
    - setuptools
    - boost-cpp
    - python
    - numpy 1.11.*
    - cython
    
  run:
    - boost-cpp
    - python
    - numpy >=1.11

test:
  source_files:
    - tests

  imports:
    - rank_filter

  commands:
    - python -m unittest discover -s .

about:
  home: http://github.com/nanshe-org/rank_filter
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: C++ boosted rank filter with Python bindings.
