language: python
python:
   - "2.7"
before_install:
   - echo "\$VIRTUAL_ENV = ${VIRTUAL_ENV}"
   - export PYTHON_EXECUTABLE=$(which python)
   - echo "\$PYTHON_EXECUTABLE = ${PYTHON_EXECUTABLE}"
   - export PYTHON_SHARED_OBJECT=$(python -c "from distutils.sysconfig import get_config_var; from os.path import join; print(join(get_config_var(\"LIBDIR\"), get_config_var(\"LDLIBRARY\")))")
   - echo "\$PYTHON_SHARED_OBJECT = ${PYTHON_SHARED_OBJECT}"
install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo add-apt-repository -y ppa:git-core/ppa
   - sudo apt-get update
   - sudo apt-get install -y make cmake git wget gcc-4.8 g++-4.8 gfortran-4.8
   - sudo apt-get install -y libopenblas-dev libhdf5-serial-dev libjpeg-dev libtiff4-dev libpng12-dev libfftw3-dev
   - sudo rm /usr/bin/cc /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
   - sudo ln -s /usr/bin/cc-4.8 /usr/bin/cc
   - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
   - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
   - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
   - pip install --upgrade pip
   - pip install -r .travis_scripts/requirements/development-stage2.txt --use-mirrors
   - sh .travis_scripts/install_boost.sh $VIRTUAL_ENV $PYTHON_EXECUTABLE
   - sh .travis_scripts/install_vigra.sh $VIRTUAL_ENV $PYTHON_SHARED_OBJECT
script:
   - export PATH=$VIRTUAL_ENV/bin:$PATH
   - export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release -DDEPENDENCY_SEARCH_PREFIX=$VIRTUAL_ENV -DVIGRA_ROOT=$VIRTUAL_ENV -DBOOST_ROOT=$VIRTUAL_ENV -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE ..
   - make
   - make check
   - make test
   - make install
