language: python
python:
   - "2.7"
before_install:
   - "export PYTHON_EXECUTABLE=$(which python)"
   - echo $PYTHON_EXECUTABLE
   - echo $VIRTUAL_ENV
install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo add-apt-repository -y ppa:git-core/ppa
   - sudo apt-get update
   - sudo apt-get install -y make cmake git gcc-4.8 g++-4.8 gfortran-4.8
   - sudo apt-get install -y libopenblas-dev libhdf5-serial-dev libjpeg-dev libtiff4-dev libpng12-dev libfftw3-dev
   - sudo rm /usr/bin/cc /usr/bin/cpp /usr/bin/gcc /usr/bin/g++
   - sudo ln -s /usr/bin/cc-4.8 /usr/bin/cc
   - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
   - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
   - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
   - pip install --upgrade pip
   - export PATH=$VIRTUAL_ENV/bin:$PATH
   - export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$LD_LIBRARY_PATH
   - sudo pip install -r .travis_scripts/requirements/development-stage2.txt --use-mirrors
   - sudo sh .travis_scripts/install_boost.sh $VIRTUAL_ENV $PYTHON_EXECUTABLE
   - sudo sh .travis_scripts/install_vigra.sh $VIRTUAL_ENV
script:
   - mkdir build && cd build
   - cmake -DCMAKE_BUILD_TYPE=Release -DDEPENDENCY_SEARCH_PREFIX=$VIRTUAL_ENV -DVIGRA_ROOT=$VIRTUAL_ENV -DBOOST_ROOT=$VIRTUAL_ENV -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE ..
   - make -j8
   - make install
