language: c++
compiler: gcc
env:
   - PYTHON_VERSION="2.7"
before_install:
   # Set environment variables.
   - export CXXFLAGS=""
   - export CXX_LDFLAGS=""
   # Move out of git directory to build root.
   - git fetch --unshallow --tags
   - git describe
   - cd ../..
   - pwd
install:
   # Update `gcc` to something with C++11 features.
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo apt-get -qq update -y
   - sudo apt-get -qq install -y gcc-4.8 g++-4.8
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
   - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10
   # Download and configure conda.
   - wget http://repo.continuum.io/miniconda/Miniconda`echo ${PYTHON_VERSION:0:1} | grep 3`-latest-Linux-x86_64.sh -O miniconda.sh
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - conda config --set always_yes yes
   - conda config --set show_channel_urls True
   - conda config --add channels nanshe
   - source activate root
   - conda update --all
   # Fix root environment to have the correct Python version.
   - touch $HOME/miniconda/conda-meta/pinned
   - echo "python ${PYTHON_VERSION}.*" >> $HOME/miniconda/conda-meta/pinned
   - conda install python=$PYTHON_VERSION
   # Install basic conda dependencies.
   - touch $HOME/miniconda/conda-meta/pinned
   - echo "conda-build ==1.16.0" >> $HOME/miniconda/conda-meta/pinned
   - conda install conda-build
   - conda install jinja2
   # Return to the git repo.
   - cd $TRAVIS_REPO_SLUG
   # Create the test environment and install dependencies.
   - conda create --use-local -n testenv python=$PYTHON_VERSION
   - source activate testenv
   # Clean up downloads as there are quite a few and they waste space/memory.
   - conda clean -tipsy
   - rm -rfv $HOME/.cache/pip
script:
   # Building the recipe will run the tests too.
   - mv .git/shallow .git/shallow-not || true
   - conda build rank_filter.recipe
   - mv .git/shallow-not .git/shallow || true
# Use container format for TravisCI.
#sudo: false  # Currently not possible as we need a newer copy of `gcc` that has C++11 features.
